/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cut: typeof import('./src/components/Cut.vue')['default']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    Header: typeof import('./src/components/Header.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    RegisterComponent: typeof import('./src/components/RegisterComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
